apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment-2024mt03042
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-2024mt03042
  template:
    metadata:
      labels:
        app: fastapi-2024mt03042
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: fastapi-container
        image: img-2024mt03042:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: metrics
        envFrom:
        - configMapRef:
            name: config-2024mt03042
