apiVersion: v1
kind: Service
metadata:
  name: fastapi-service-2024mt03042
  labels:
    team: frontend
spec:
  type: LoadBalancer
  selector:
    app: fastapi-2024mt03042
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: fastapi-2024mt03042
